<main>
<article class="day-desc"><h2>--- Day 3: Rucksack Reorganization ---</h2><p>One Elf has the important job of loading all of the <a href="https://en.wikipedia.org/wiki/Rucksack" target="_blank">rucksacks</a> with supplies for the <span title="Where there's jungle, there's hijinxs.">jungle</span> journey. Unfortunately, that Elf didn't quite follow the packing instructions, and so a few items now need to be rearranged.</p>
<p>Each rucksack has two large <em>compartments</em>. All items of a given type are meant to go into exactly one of the two compartments. The Elf that did the packing failed to follow this rule for exactly one item type per rucksack.</p>
<p>The Elves have made a list of all of the items currently in each rucksack (your puzzle input), but they need your help finding the errors. Every item type is identified by a single lowercase or uppercase letter (that is, <code>a</code> and <code>A</code> refer to different types of items).</p>
<p>The list of items for each rucksack is given as characters all on a single line. A given rucksack always has the same number of items in each of its two compartments, so the first half of the characters represent items in the first compartment, while the second half of the characters represent items in the second compartment.</p>
<p>For example, suppose you have the following list of contents from six rucksacks:</p>
<pre><code>vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw
</code></pre>
<ul>
<li>The first rucksack contains the items <code>vJrwpWtwJgWrhcsFMMfFFhFp</code>, which means its first compartment contains the items <code>vJrwpWtwJgWr</code>, while the second compartment contains the items <code>hcsFMMfFFhFp</code>. The only item type that appears in both compartments is lowercase <code><em>p</em></code>.</li>
<li>The second rucksack's compartments contain <code>jqHRNqRjqzjGDLGL</code> and <code>rsFMfFZSrLrFZsSL</code>. The only item type that appears in both compartments is uppercase <code><em>L</em></code>.</li>
<li>The third rucksack's compartments contain <code>PmmdzqPrV</code> and <code>vPwwTWBwg</code>; the only common item type is uppercase <code><em>P</em></code>.</li>
<li>The fourth rucksack's compartments only share item type <code><em>v</em></code>.</li>
<li>The fifth rucksack's compartments only share item type <code><em>t</em></code>.</li>
<li>The sixth rucksack's compartments only share item type <code><em>s</em></code>.</li>
</ul>
<p>To help prioritize item rearrangement, every item type can be converted to a <em>priority</em>:</p>
<ul>
<li>Lowercase item types <code>a</code> through <code>z</code> have priorities 1 through 26.</li>
<li>Uppercase item types <code>A</code> through <code>Z</code> have priorities 27 through 52.</li>
</ul>
<p>In the above example, the priority of the item type that appears in both compartments of each rucksack is 16 (<code>p</code>), 38 (<code>L</code>), 42 (<code>P</code>), 22 (<code>v</code>), 20 (<code>t</code>), and 19 (<code>s</code>); the sum of these is <code><em>157</em></code>.</p>
<p>Find the item type that appears in both compartments of each rucksack. <em>What is the sum of the priorities of those item types?</em></p>
</article>

In [1]:
input = readlines("src/main/resources/input3.txt")

300-element Vector{String}:
 "rGnRRccfcCRFDPqNWdwWJWRBdB"
 "jZzVVSZSjmQvZTSZfjmLzNPJqWtJBwqpNtBpdWdNvd"
 "fZfjlMLVshMFhcHnDG"
 "vJRmRfJbfRfJsCpvgLggNVsv"
 "zlzSrMPZMgBFFMNMVWsjsF"
 "dzBSBlzdcggRGdndnn"
 "hNwqVDVDdmQwQPrbDMSSMRSWSM"
 "LvnzJJtlcHstlffCVpMSbRMpBMbCgVWM"
 "lGvvscLHcfsHtvlsnZmmNGhNFVQqqTdqFd"
 "sHGzGsfcZnHfhbLRFrdrhRFf"
 "vwVqzSSjSSttjSqgNMqwzSSVCCgRPhPhFLdCRLLrdCRRrDLb"
 "vvwwtvvVwSvMQzjvmNtJsHBnsZllmnnTBBcBlTnW"
 "pzNVBVplhfLfVfVStZrZHbQHZQTb"
 ⋮
 "wRbGbqqGCwnGTRqBqlMVphpgMgMFdnFVnt"
 "cgzvssscgHJVdhDdhDMvDM"
 "PjcZcsJrJHWgrPBQmCqRBPSSRCSb"
 "rHBmLlPLlTzztvRtGsVL"
 "NWJJWWjJDJWWhphqwCFCwzvRVcgRtctRgNNVVscsGc"
 "hqCCsnCpCDnbCnWhwpbHbBHmMBMMmdPrZfdP"
 "GRPprPQdsprGpGgGTlqfVqnZLgnLnwNZLw"
 "CCWJMMvhhCvthtCjvDWFjMcCVZJLNnfqnllwzlzNnzzwVNnN"
 "cDtZFjDjcMCDDtZFSMCvvDpmsmSRRpmmbSpdPRdTmTsp"
 "mmPpsbZZbbzvzgbrZRPgPMWqtHtqDnGCnMWCDwGHwtwW"
 "cBFBNNccsTLjJjfcjfGDGQtWwFCnCGtqCCQH"
 "TNsTLJlffdldzvrmbmrPzp"

In [2]:
split_rucksack_compartments(x) = (
    collect(SubString(x, 1, Int(length(x)/2))),
    collect(SubString(x, Int(length(x)/2) + 1, length(x)))
)
rucksack_compartments = map(split_rucksack_compartments, input)

300-element Vector{Tuple{Vector{Char}, Vector{Char}}}:
 (['r', 'G', 'n', 'R', 'R', 'c', 'c', 'f', 'c', 'C', 'R', 'F', 'D'], ['P', 'q', 'N', 'W', 'd', 'w', 'W', 'J', 'W', 'R', 'B', 'd', 'B'])
 (['j', 'Z', 'z', 'V', 'V', 'S', 'Z', 'S', 'j', 'm'  …  'v', 'Z', 'T', 'S', 'Z', 'f', 'j', 'm', 'L', 'z'], ['N', 'P', 'J', 'q', 'W', 't', 'J', 'B', 'w', 'q'  …  'N', 't', 'B', 'p', 'd', 'W', 'd', 'N', 'v', 'd'])
 (['f', 'Z', 'f', 'j', 'l', 'M', 'L', 'V', 's'], ['h', 'M', 'F', 'h', 'c', 'H', 'n', 'D', 'G'])
 (['v', 'J', 'R', 'm', 'R', 'f', 'J', 'b', 'f', 'R', 'f', 'J'], ['s', 'C', 'p', 'v', 'g', 'L', 'g', 'g', 'N', 'V', 's', 'v'])
 (['z', 'l', 'z', 'S', 'r', 'M', 'P', 'Z', 'M', 'g', 'B'], ['F', 'F', 'M', 'N', 'M', 'V', 'W', 's', 'j', 's', 'F'])
 (['d', 'z', 'B', 'S', 'B', 'l', 'z', 'd', 'c'], ['g', 'g', 'R', 'G', 'd', 'n', 'd', 'n', 'n'])
 (['h', 'N', 'w', 'q', 'V', 'D', 'V', 'D', 'd', 'm', 'Q', 'w', 'Q'], ['P', 'r', 'b', 'D', 'M', 'S', 'S', 'M', 'R', 'S', 'W', 'S', 'M'])
 (['L', 'v', 'n', 'z', 'J',

In [3]:
find_errors(compartments) = intersect(compartments[1], compartments[2])[1]
errors = map(find_errors, rucksack_compartments)

300-element Vector{Char}:
 'R': ASCII/Unicode U+0052 (category Lu: Letter, uppercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'M': ASCII/Unicode U+004D (category Lu: Letter, uppercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'M': ASCII/Unicode U+004D (category Lu: Letter, uppercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'D': ASCII/Unicode U+0044 (category Lu: Letter, uppercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 'G': ASCII/Unicode U+0047 (category Lu: Letter, uppercase)
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'm': ASCII/Unicode U+006D (category Ll: Letter, lowercase)
 'V': ASCII/Unicode U+0056 (category Lu: Letter, uppercase)
 ⋮
 'n': ASCII/Unicode U+006E (category Ll: Letter, lowercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'P': ASCII/Unicode U+0050 (category Lu: Letter, uppercase)
 'L': ASCII

In [4]:
priority(x) = Int(x) - if islowercase(x) 96 else 38 end
sum(map(priority, errors))

7826

<article class="day-desc"><h2 id="part2">--- Part Two ---</h2><p>As you finish identifying the misplaced items, the Elves come to you with another issue.</p>
<p>For safety, the Elves are divided into groups of three. Every Elf carries a badge that identifies their group. For efficiency, within each group of three Elves, the badge is the <em>only item type carried by all three Elves</em>. That is, if a group's badge is item type <code>B</code>, then all three Elves will have item type <code>B</code> somewhere in their rucksack, and at most two of the Elves will be carrying any other item type.</p>
<p>The problem is that someone forgot to put this year's updated authenticity sticker on the badges. All of the badges need to be pulled out of the rucksacks so the new authenticity stickers can be attached.</p>
<p>Additionally, nobody wrote down which item type corresponds to each group's badges. The only way to tell which item type is the right one is by finding the one item type that is <em>common between all three Elves</em> in each group.</p>
<p>Every set of three lines in your list corresponds to a single group, but each group can have a different badge item type. So, in the above example, the first group's rucksacks are the first three lines:</p>
<pre><code>vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
</pre></code>
<p>And the second group's rucksacks are the next three lines:</p>
<pre><code>wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw
</code></pre>
<p>In the first group, the only item type that appears in all three rucksacks is lowercase <code>r</code>; this must be their badges. In the second group, their badge item type must be <code>Z</code>.</p>
<p>Priorities for these items must still be found to organize the sticker attachment efforts: here, they are 18 (<code>r</code>) for the first group and 52 (<code>Z</code>) for the second group. The sum of these is <code><em>70</em></code>.</p>
<p>Find the item type that corresponds to the badges of each three-Elf group. <em>What is the sum of the priorities of those item types?</em></p>
</article>

In [5]:
? Iterators.partition

```
partition(collection, n)
```

Iterate over a collection `n` elements at a time.

# Examples

```jldoctest
julia> collect(Iterators.partition([1,2,3,4,5], 2))
3-element Vector{SubArray{Int64, 1, Vector{Int64}, Tuple{UnitRange{Int64}}, true}}:
 [1, 2]
 [3, 4]
 [5]
```


In [6]:
elf_groups = collect(Iterators.partition(input, 3))

100-element Vector{SubArray{String, 1, Vector{String}, Tuple{UnitRange{Int64}}, true}}:
 ["rGnRRccfcCRFDPqNWdwWJWRBdB", "jZzVVSZSjmQvZTSZfjmLzNPJqWtJBwqpNtBpdWdNvd", "fZfjlMLVshMFhcHnDG"]
 ["vJRmRfJbfRfJsCpvgLggNVsv", "zlzSrMPZMgBFFMNMVWsjsF", "dzBSBlzdcggRGdndnn"]
 ["hNwqVDVDdmQwQPrbDMSSMRSWSM", "LvnzJJtlcHstlffCVpMSbRMpBMbCgVWM", "lGvvscLHcfsHtvlsnZmmNGhNFVQqqTdqFd"]
 ["sHGzGsfcZnHfhbLRFrdrhRFf", "vwVqzSSjSSttjSqgNMqwzSSVCCgRPhPhFLdCRLLrdCRRrDLb", "vvwwtvvVwSvMQzjvmNtJsHBnsZllmnnTBBcBlTnW"]
 ["pzNVBVplhfLfVfVStZrZHbQHZQTb", "sdPPJdCjbdQHMTWt", "ngmJGFjJwJCmGcnJcFtgwcDBNLlqfBpvfBpqllhlfL"]
 ["TGpphMZhJQpGLZTMCCtsBMCSDsStBFcB", "jdfgHClHrdrbWvWgjqmctSDqltDsFFDFBc", "dNWWvfgCLzzNNLZz"]
 ["vvHzBrTSvHFbqZqZTBBtzdVfGCGhJSfGJGDSdGMhVG", "lgmgslssslscsnRlVGWGWGVMRCll", "pQPsjwnNgQmnNNwQgNLNnmgZqvFqtwqtrMMzvzwFtrqTrr"]
 ["TNhNLTrswwsnFNrrGZVnJnZmVpSjjVDnPp", "dBlzzCBqgfWMBpPSJDHVZSVP", "cqzfpcdcNFFGrhcb"]
 ["LLpzCzSzJnLQVnTNhQ", "vtDqwBcRztQbthtV", "qZZZqZvvsZwwjvjDjspFlPpSSCslpzPlls"]
 ["rsZ

In [7]:
find_badge(elf_group) = intersect(elf_group[1], elf_group[2], elf_group[3])[1]
badges = map(find_badge, elf_groups)

100-element Vector{Char}:
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'V': ASCII/Unicode U+0056 (category Lu: Letter, uppercase)
 'z': ASCII/Unicode U+007A (category Ll: Letter, lowercase)
 't': ASCII/Unicode U+0074 (category Ll: Letter, lowercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 'M': ASCII/Unicode U+004D (category Lu: Letter, uppercase)
 'p': ASCII/Unicode U+0070 (category Ll: Letter, lowercase)
 'z': ASCII/Unicode U+007A (category Ll: Letter, lowercase)
 'V': ASCII/Unicode U+0056 (category Lu: Letter, uppercase)
 'z': ASCII/Unicode U+007A (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 ⋮
 'G': ASCII/Unicode U+0047 (category Lu: Letter, uppercase)
 'm': ASCII/Unicode U+006D (category Ll: Letter, lowercase)
 'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)
 'h': ASCII

In [8]:
sum(map(priority, badges))

2577